
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[464] =
    {   0,
        0,    0,  103,  101,  100,  100,   89,  101,   95,   88,
      101,   83,   84,   93,   92,   80,   91,   87,   94,   60,
       60,   82,   77,   96,   81,   97,   57,   57,   57,   57,
       57,   57,   85,   86,   98,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   78,   99,   79,   90,   76,    0,   65,
        0,   79,   71,    0,    0,    0,    0,    0,    0,    0,
        0,   68,   69,   70,   63,   64,   59,    0,   60,    0,
       60,   86,   78,   85,   67,   73,   75,   74,   66,   57,
       57,   57,    0,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   57,   57,   57,   57,   57,    7,   57,
       57,   14,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   72,   61,
        0,    0,    0,    0,    0,    0,    0,    0,   63,   63,
        0,   64,   59,    0,   62,   58,   57,   34,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,    6,   57,    8,   57,   19,   57,   57,   57,
       57,   13,   56,   57,   57,   57,   40,   57,   57,   57,
       57,   57,   57,   57,    0,    0,    0,    0,    0,    0,
        0,    0,   63,    0,   63,    0,   64,   62,   58,   57,

       28,   57,   57,   57,   57,    2,   57,   57,   57,   57,
       57,    4,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   24,   12,   57,   57,   43,   57,
       57,   10,   41,   57,   20,    0,    0,    0,    0,    0,
       63,   57,   57,   57,   57,    1,   57,   15,   57,   57,
       57,   57,    5,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   11,    0,    0,    0,   57,   55,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   35,   57,   57,   57,

       57,   57,   57,   57,   57,    9,   57,   57,   57,   32,
        0,    0,   16,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
        0,    0,   57,   39,   57,    3,   37,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   33,   57,   57,   57,   57,   25,    0,
       17,   57,   57,   30,   57,   57,   57,   47,   57,   57,
       57,   57,   57,   57,   22,   23,   57,   57,   57,   57,
       57,   57,   57,    0,   57,   57,   57,   57,   57,   57,

       57,   46,   57,   57,   57,   49,   57,   57,   57,   57,
       18,   57,   57,   21,   42,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   31,   29,   50,   57,
       57,   48,   57,   57,   57,   57,   53,   57,   57,   38,
       57,   57,   57,   57,   52,   54,   57,   27,   36,   57,
       57,   57,   26,   57,   51,   57,   57,   45,   57,   57,
       57,   44,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   27,   28,   29,   30,   31,
       32,   32,   33,   34,   32,   35,   36,   32,   32,   37,
       32,   38,   39,   32,   40,   32,   32,   41,   32,   32,
       42,   43,   44,   45,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   41,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    1,    4,    3,    3,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[468] =
    {   0,
        0,    0,  700,  701,  701,  701,  675,   71,  673,  690,
       51,  701,  701,  701,  684,  701,   64,   63,  701,  102,
       88,  670,  701,   78,  670,   61,    0,  635,  631,   80,
      640,  626,  701,  701,  701,  637,  624,   37,   41,   51,
       32,  636,   73,   49,  108,  635,  638,  620,   64,   63,
      622,  621,   87,  701,  608,  701,  701,  701,  107,  701,
      677,  701,  701,  116,  128,  132,  137,  141,  139,  140,
      144,  701,  701,  701,  159,  183,  207,  179,  172,    0,
      231,  701,  701,  701,  701,  701,  701,  701,  701,    0,
      612,  630,  634,  616,  616,  613,  621,  621,  624,   90,

      610,  622,  603,  602,  616,  604,  600,  597,    0,  596,
      126,    0,  613,  614,  613,  598,  600,  597,  596,  593,
      587,  592,  120,  603,  588,  594,  593,  592,  701,  701,
      176,  180,  200,  201,  213,  177,  221,  261,  701,  266,
      288,  701,  196,  273,  292,  237,  581,    0,  588,  583,
      594,  587,  594,  576,  590,  573,  571,  586,  586,  583,
      587,  193,    0,  586,    0,   92,    0,  585,  571,  570,
      571,    0,  199,  576,  577,  558,    0,  560,  561,  563,
      560,  570,  553,  560,  225,  244,  245,  286,  291,  295,
      305,  302,  322,  344,  701,  313,  350,  701,  320,  551,

        0,  552,  564,  554,  556,    0,  555,  545,  555,  551,
      561,    0,  545,  540,  540,  332,  540,  536,  547,  550,
      549,  553,  250,  534,    0,  546,  532,  529,    0,  539,
      535,    0,    0,  541,  701,  308,  363,  329,  357,  378,
      392,  540,  520,  524,  533,    0,  541,    0,  526,  530,
      520,  522,    0,  536,  513,  529,  521,  517,  526,  512,
      514,  514,  523,  513,  512,  287,  519,  514,  498,  502,
      506,  519,  498,  502,    0,  375,  378,  381,  498,    0,
      496,  494,  494,  491,  497,  506,  500,  490,  506,  505,
      490,  502,  490,  487,  498,  486,    0,  484,  483,  496,

      495,  478,  469,  493,  473,    0,  475,  490,  482,  701,
      382,  385,    0,  473,  463,  470,  480,  479,  483,  468,
      476,  471,  475,  462,  477,  461,  472,  469,  464,  454,
      453,  456,  453,  447,  462,  446,  450,  449,  453,  438,
      391,  393,  443,    0,  455,    0,    0,  449,  438,  440,
      444,  443,  435,  452,  434,  301,  432,  436,  425,  424,
      443,  445,  436,    0,  420,  425,  433,  426,    0,  395,
        0,  435,  424,    0,  417,  436,  427,  435,  428,  409,
      412,  412,  411,  418,    0,    0,  395,  414,  398,  399,
      395,  399,  410,  396,  406,  407,  399,  405,  391,  384,

      396,    0,  377,  381,  384,    0,  388,  386,  389,  386,
        0,  369,  368,    0,    0,  366,  371,  375,  360,  365,
      357,  355,  351,  363,  341,  355,    0,    0,    0,  341,
      326,    0,  324,  313,  308,  285,    0,  280,  273,    0,
      278,  280,  225,  214,    0,    0,  213,    0,    0,  200,
      207,  149,    0,  155,    0,  122,  115,    0,  104,   98,
       88,    0,  701,  465,  469,  471,  101
    } ;

static yyconst flex_int16_t yy_def[468] =
    {   0,
      463,    1,  463,  463,  463,  463,  463,  464,  463,  463,
      465,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  466,  466,  466,  466,
      466,  466,  463,  463,  463,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  463,  463,  463,  463,  463,  464,  463,
      464,  463,  463,  465,  465,  465,  465,  465,  465,  465,
      465,  463,  463,  463,  463,  463,  463,  463,  463,  467,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  466,
      466,  466,  465,  466,  466,  466,  466,  466,  466,  466,

      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  463,  463,
      465,  465,  465,  465,  465,  465,  465,  463,  463,  463,
      463,  463,  463,  463,  463,  467,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  465,  465,  465,  465,  465,  465,
      465,  463,  463,  463,  463,  463,  463,  463,  463,  466,

      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  463,  465,  465,  465,  465,  463,
      463,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  465,  465,  465,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,

      466,  466,  466,  466,  466,  466,  466,  466,  466,  463,
      465,  465,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      465,  465,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  465,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  465,  466,  466,  466,  466,  466,  466,

      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,    0,  463,  463,  463,  463
    } ;

static yyconst flex_uint16_t yy_nxt[777] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,   26,   27,   27,   28,   27,   27,
       27,   27,   27,   29,   30,   31,   32,   27,   27,   27,
       27,   33,    4,   34,   35,   27,   36,   37,   38,   39,
       40,   41,   42,   27,   43,   44,   27,   45,   46,   47,
       27,   48,   27,   49,   50,   51,   27,   52,   53,   27,
       27,   54,   55,   56,   57,   60,   65,   73,   66,   75,
       75,   75,   75,   83,   88,   89,   67,   93,   74,  106,
       99,  102,  107,   68,  100,  103,  112,  101,   84,   69,

       85,   86,   76,  146,   81,   81,   81,   81,  104,  113,
      105,   60,   70,   61,  121,   71,   76,   78,   77,   77,
       77,   77,   79,  130,  109,  114,  115,   79,  123,  124,
      122,   78,  110,  127,   94,  130,   79,  111,   78,  130,
      128,   79,   80,  463,  130,   79,  130,  130,   64,   61,
      155,  130,   78,  217,   79,  218,  156,  462,   68,   79,
      133,  461,  116,  131,  460,  132,  178,  117,   79,  134,
       68,  166,  167,  459,   68,   75,   75,   75,   75,   68,
      179,   68,   68,  130,  130,  135,   68,  130,  138,  139,
      144,  458,  144,  139,  137,  145,  145,  145,  145,  140,

      140,  140,  140,  136,  185,  457,   79,  130,  130,  138,
      139,   79,  141,  142,  456,  186,  139,  142,   68,   68,
      130,   76,   68,   77,   77,   77,   77,  187,  130,   79,
      143,  190,  235,  141,  142,  143,   78,  188,   79,  214,
      142,  143,   68,   68,  223,   76,  143,   81,   81,   81,
       81,  235,  235,  143,  215,   68,  455,   78,  454,  224,
       78,  189,  143,   68,  143,   79,  453,   68,  452,  191,
       79,  199,  192,  143,  192,  451,  199,  193,  193,  193,
      193,   78,  140,  140,  140,  140,   68,   68,   79,  145,
      145,  145,  145,  130,  199,  194,  195,   79,  130,  196,

      195,  196,  130,  199,  197,  197,  197,  197,  145,  145,
      145,  145,  130,  267,  268,  235,  194,  195,  193,  193,
      193,  193,  198,  195,  236,  450,  198,  449,   68,  197,
      197,  197,  197,   68,  300,  301,  130,   68,  193,  193,
      193,  193,  448,  198,  237,  447,  381,   68,  446,  198,
       68,  382,  139,  238,  199,  240,  139,  240,  445,  199,
      241,  241,  241,  241,  130,  239,  197,  197,  197,  197,
      130,   68,  444,  139,  443,  277,  442,  199,  255,  139,
      142,  256,  310,  257,  142,  130,  199,  258,  130,  130,
      259,  441,  130,  260,  241,  241,  241,  241,  310,   68,

      130,  142,  130,  310,  440,   68,  439,  142,  241,  241,
      241,  241,  438,  276,  437,  436,  278,   68,  435,  434,
       68,  433,  195,   68,   68,  432,  195,   68,  431,  430,
      312,  342,  429,   68,  428,   68,  427,   68,   68,  426,
      425,  311,  424,  195,  423,  422,  421,  420,  419,  195,
      418,  341,  417,  416,  415,  414,  370,  413,  412,  411,
      410,  409,  408,  407,  394,   59,   59,   59,   59,   64,
      406,   64,   64,   90,   90,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  396,  395,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  380,  379,  378,

      377,  376,  375,  374,  373,  372,  371,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  345,  344,  343,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  309,  308,  307,  306,  305,  304,  303,  302,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  275,  274,  273,  272,  271,  270,  269,  266,  265,

      264,  263,  262,  261,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  222,  221,  220,
      219,  216,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  184,  183,  182,  181,
      180,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  165,  164,  163,  162,  161,  160,  159,  158,  157,
      154,  153,  152,  151,  150,  149,   68,  148,  147,  463,
      129,  126,  125,  120,  119,  118,  108,   98,   97,   96,
       95,   92,   91,   87,   82,   72,   63,   62,   58,  463,

        3,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463
    } ;

static yyconst flex_int16_t yy_chk[777] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,   11,   17,   11,   18,
       18,   18,   18,   24,   26,   26,   11,   30,   17,   41,
       38,   39,   41,   11,   38,   39,   44,   38,   24,   11,

       24,   24,   21,  467,   21,   21,   21,   21,   40,   44,
       40,   59,   11,    8,   49,   11,   20,   21,   20,   20,
       20,   20,   21,   64,   43,   45,   45,   21,   50,   50,
       49,   20,   43,   53,   30,   65,   20,   43,   21,   66,
       53,   20,   20,   68,   67,   21,   69,   70,   68,   59,
      100,   71,   20,  166,   21,  166,  100,  461,   64,   20,
       66,  460,   45,   65,  459,   65,  123,   45,   20,   67,
       65,  111,  111,  457,   66,   75,   75,   75,   75,   67,
      123,   69,   70,  131,  136,   69,   71,  132,   75,   75,
       78,  456,   78,   75,   71,   78,   78,   78,   78,   76,

       76,   76,   76,   70,  131,  454,   79,  133,  134,   75,
       75,   79,   76,   76,  452,  132,   75,   76,  131,  136,
      135,   77,  132,   77,   77,   77,   77,  133,  137,   79,
      143,  136,  185,   76,   76,  143,   77,  134,   79,  162,
       76,   77,  133,  134,  173,   81,   77,   81,   81,   81,
       81,  186,  187,  143,  162,  135,  451,   77,  450,  173,
       81,  135,  143,  137,   77,   81,  447,  185,  444,  137,
       81,  146,  138,   77,  138,  443,  146,  138,  138,  138,
      138,   81,  140,  140,  140,  140,  186,  187,   81,  144,
      144,  144,  144,  188,  146,  140,  140,   81,  189,  141,

      140,  141,  190,  146,  141,  141,  141,  141,  145,  145,
      145,  145,  191,  223,  223,  236,  140,  140,  192,  192,
      192,  192,  145,  140,  188,  442,  145,  441,  188,  196,
      196,  196,  196,  189,  266,  266,  238,  190,  193,  193,
      193,  193,  439,  145,  189,  438,  356,  191,  436,  145,
      236,  356,  193,  190,  199,  194,  193,  194,  435,  199,
      194,  194,  194,  194,  239,  191,  197,  197,  197,  197,
      237,  238,  434,  193,  433,  238,  431,  199,  216,  193,
      197,  216,  276,  216,  197,  277,  199,  216,  278,  311,
      216,  430,  312,  216,  240,  240,  240,  240,  341,  239,

      342,  197,  370,  394,  426,  237,  425,  197,  241,  241,
      241,  241,  424,  237,  423,  422,  239,  276,  421,  420,
      277,  419,  241,  278,  311,  418,  241,  312,  417,  416,
      278,  312,  413,  341,  412,  342,  410,  370,  394,  409,
      408,  277,  407,  241,  405,  404,  403,  401,  400,  241,
      399,  311,  398,  397,  396,  395,  342,  393,  392,  391,
      390,  389,  388,  387,  370,  464,  464,  464,  464,  465,
      384,  465,  465,  466,  466,  383,  382,  381,  380,  379,
      378,  377,  376,  375,  373,  372,  368,  367,  366,  365,
      363,  362,  361,  360,  359,  358,  357,  355,  354,  353,

      352,  351,  350,  349,  348,  345,  343,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  309,  308,  307,  305,  304,  303,
      302,  301,  300,  299,  298,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  279,  274,  273,  272,  271,  270,  269,  268,  267,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  252,  251,  250,  249,  247,  245,  244,  243,
      242,  234,  231,  230,  228,  227,  226,  224,  222,  221,

      220,  219,  218,  217,  215,  214,  213,  211,  210,  209,
      208,  207,  205,  204,  203,  202,  200,  184,  183,  182,
      181,  180,  179,  178,  176,  175,  174,  171,  170,  169,
      168,  164,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  147,  128,  127,  126,  125,
      124,  122,  121,  120,  119,  118,  117,  116,  115,  114,
      113,  110,  108,  107,  106,  105,  104,  103,  102,  101,
       99,   98,   97,   96,   95,   94,   93,   92,   91,   61,
       55,   52,   51,   48,   47,   46,   42,   37,   36,   32,
       31,   29,   28,   25,   22,   15,   10,    9,    7,    3,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "grammar.lex"
#line 9 "grammar.lex"
#include <stdio.h>
#include "table.h"

void count();
#line 795 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 15 "grammar.lex"


#line 1016 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 464 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 701 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 17 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","BREAK"); return(BREAK);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CHAR"); return(CHAR);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 19 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CONTINUE"); return(CONTINUE);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 20 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","ELSE"); return(ELSE);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 21 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","FLOAT"); return(FLOAT);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 22 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","FOR"); return(FOR);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 23 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","IF"); return(IF);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 24 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","INT"); return(INT);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 25 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","RETURN"); return(RETURN);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 26 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","VOID"); return(VOID);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 27 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","WHILE"); return(WHILE);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 28 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","PROC"); return(PROC);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 29 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","LNK"); return(LNK);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 30 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","JB"); return(JB);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 31 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CLUST"); return(CLUST);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 32 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CLUSTER"); return(CLUSTER);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 33 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","PROCESSOR"); return(PROCESSOR);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 34 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","PROCESSORS"); return(PROCESSORS);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 35 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","ISA"); return(ISA);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 36 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","PROC_TYPE"); return(PROC_TYPE);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 37 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CLOCK_SPEED"); return(CLOCK_SPEED);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 38 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","MEM1"); return(MEM1);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 39 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","MEM2"); return(MEM2);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 40 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","NAME"); return(NAME);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 41 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","TOPOLOGY"); return(TOPOLOGY);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 42 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","LINK_BANDWIDTH"); return(LINK_BANDWIDTH);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 43 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","LINK_CAPACITY"); return(LINK_CAPACITY);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 44 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","LINK"); return(LINK);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 45 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","START_POINT"); return(START_POINT);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 46 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","END_POINT"); return(END_POINT);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 47 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","MEMORY_TYPE"); return(MEMORY_TYPE);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 48 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","MEM_TYPE"); return(MEM_TYPE);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 49 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","MEMORY_SIZE"); return(MEMORY_SIZE);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 50 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","JOB"); return(JOB);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 51 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","JOB_ID"); return(JOB_ID);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 52 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","FLOPS_REQUIRED"); return(FLOPS_REQUIRED);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 53 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","DEADLINE"); return(DEADLINE);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 54 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","MEM_REQUIRED"); return(MEM_REQUIRED);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 55 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","AFFINITY"); return(AFFINITY);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 56 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","RUN"); return(RUN);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 57 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","WAIT"); return(WAIT);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 58 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","DISCARD_JOB"); return(DISCARD_JOB);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 59 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","STOP"); return(STOP);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 60 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","GET_AVAILABLE_MEMORY"); return(GET_AVAILABLE_MEMORY);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 61 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","GET_JOB_AFFINITY"); return(GET_JOB_AFFINITY);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 62 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","GET_JOB_MEMORY"); return(GET_JOB_MEMORY);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 63 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","GET_FLOPS"); return(GET_FLOPS);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 64 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","GET_DEADLINE"); return(GET_DEADLINE);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 65 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","IS_RUNNING"); return(IS_RUNNING);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 66 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","SUBMIT_JOBS"); return(SUBMIT_JOBS);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 67 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","GET_FLOPS_SPEED"); return(GET_FLOPS_SPEED);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 68 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","GET_PROC_TYPE"); return(GET_PROC_TYPE);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 69 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","IS_PROCESSOR"); return(IS_PROCESSOR);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 70 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","GET_PROCESSOR"); return(GET_PROCESSOR);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 71 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","MEMORY"); return(MEMORY);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 72 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","MEM"); return(MEM);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 74 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","IDENTIFIER"); return(IDENTIFIER);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 76 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CONSTANT"); return(CONSTANT);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 77 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CONSTANT"); return(CONSTANT);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 78 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CONSTANT"); return(CONSTANT);}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 79 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CONSTANT"); return(CONSTANT);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 81 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CONSTANT"); return(CONSTANT);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 82 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CONSTANT"); return(CONSTANT);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 83 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","CONSTANT"); return(CONSTANT);}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 85 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","STRING_LITERAL"); return(STRING_LITERAL);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 87 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","RIGHT_OP"); return(RIGHT_OP);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 88 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","LEFT_OP"); return(LEFT_OP);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 89 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","INC_OP"); return(INC_OP);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 90 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","DEC_OP"); return(DEC_OP);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 91 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","DREF_OP"); return(DREF_OP);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 92 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","AND_OP"); return(AND_OP);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 93 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","OR_OP"); return(OR_OP);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 94 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","LE_OP"); return(LE_OP);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 95 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","GE_OP"); return(GE_OP);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 96 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","EQ_OP"); return(EQ_OP);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 97 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","NE_OP"); return(NE_OP);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 98 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","SEMI_COLON"); return(SEMI_COLON);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 99 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","LEFT_CURLY"); return(LEFT_CURLY);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 100 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","RIGHT_CURLY"); return(RIGHT_CURLY);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 101 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","COMMA"); return(COMMA);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 102 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","ASGN_OP"); return(ASGN_OP);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 103 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","ASGN_OP"); return(ASGN_OP);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 104 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","LEFT_PARENTEHSIS"); return(LEFT_PARENTEHSIS);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 105 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","RIGHT_PARENTHESIS"); return(RIGHT_PARENTHESIS);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 106 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","LEFT_BRACKET"); return(LEFT_BRACKET);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 107 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","RIGHT_BRACKET"); return(RIGHT_BRACKET);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 108 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","DOT"); return(DOT);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 109 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","AMPERSAND"); return(AMPERSAND);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 110 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","NOT_OP"); return(NOT_OP);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 111 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","BTW_NOT"); return(BTW_NOT);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 112 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","MINUS"); return(MINUS);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 113 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","PLUS"); return(PLUS);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 114 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","MUL_OP"); return(MUL_OP);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 115 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","DIV_OP"); return(DIV_OP);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 116 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","MOD_OP"); return(MOD_OP);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 117 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","LESS_THAN"); return(LESS_THAN);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 118 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","GREATER_THAN"); return(GREATER_THAN);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 119 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","XOR_OP"); return(XOR_OP);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 120 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","BTW_OR"); return(BTW_OR);}
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 122 "grammar.lex"
{ count();}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 123 "grammar.lex"
{ printf("<"); count(); printf(",%s> ","INVALID"); return(INVALID);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 125 "grammar.lex"
ECHO;
	YY_BREAK
#line 1586 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 464 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 464 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 463);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 125 "grammar.lex"



int yywrap()
{
	return(1);
}


int column = 0;

void count()
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;

	ECHO;
}



