#define BREAK						0
#define	CHAR						1
#define	CONTINUE					2
#define	ELSE						3
#define	FLOAT						4
#define	FOR							5
#define	IF							6
#define	INT							7
#define	RETURN						8
#define	VOID						9
#define	WHILE						10
#define	PROC						11
#define	LNK							12
#define	JB							13
#define	CLUST						14
#define	CLUSTER						15
#define	PROCESSOR					16
#define	ISA							17
#define	PROC_TYPE					18
#define	CLOCK_SPEED					19
#define	MEM1						20
#define	MEM2						21
#define	NAME  						22
#define	TOPOLOGY					23
#define	LINK_BANDWIDTH				24
#define	LINK_CAPACITY				25
#define	LINK						26
#define	START_POINT					27
#define	END_POINT					28
#define	MEMORY_TYPE					29
#define	MEM_TYPE					30
#define	MEMORY_SIZE					31
#define	JOB							32
#define	JOB_ID						33
#define	FLOPS_REQUIRED				34
#define	DEADLINE					35
#define	MEM_REQUIRED				36
#define	AFFINITY					37
#define	RUN							38
#define	WAIT						39
#define	DISCARD_JOB					40
#define	STOP						41
#define	GET_AVAILABLE_MEMORY		42
#define	GET_JOB_AFFINITY			43
#define	GET_JOB_MEMORY				44
#define	GET_FLOPS					45
#define	GET_DEADLINE				46
#define	IS_RUNNING					47
#define	SUBMIT_JOBS					48
#define	GET_FLOPS_SPEED				49
#define	GET_PROC_TYPE				50
#define	IS_PROCESSOR				51
#define	GET_PROCESSOR				52
#define	MEM							53							
#define	IDENTIFIER					54
#define	CONSTANT					55
#define	STRING_LITERAL				56
#define	RIGHT_OP					57
#define	LEFT_OP						58
#define	INC_OP						59
#define	DEC_OP						60
#define	DREF_OP						61
#define	AND_OP						62
#define	OR_OP						63							
#define	LE_OP						64
#define	GE_OP						65
#define	EQ_OP						66
#define	NE_OP						67
#define	SEMI_COLON					68
#define	LEFT_CURLY					69
#define	RIGHT_CURLY					70
#define	COMMA						71
#define	ASGN_OP						72
#define	LEFT_PARENTEHSIS			73
#define	RIGHT_PARENTHESIS			74
#define	LEFT_BRACKET				75
#define	RIGHT_BRACKET				76
#define	DOT							77
#define	AMPERSAND					78
#define	NOT_OP						79
#define	BTW_NOT						80
#define	MINUS						81
#define	PLUS						82
#define	MUL_OP						83
#define	DIV_OP						84
#define	MOD_OP						85
#define	LESS_THAN					86
#define	GREATER_THAN				87
#define	XOR_OP						88
#define	BTW_OR						89
#define	INVALID						90
#define MEMORY 						91
#define PROCESSORS					92